x = input ('Digite algo: ')
print ('Tipo primitivo:', type (x))
print ('É número?', x.isnumeric ())
print ('É alfabético?', x.isalpha ())
print ('Está em maiúsculo?',x.isupper ())
print ('Está em minúsculo?',x.islower ())
print ('É decimal?', x.isdecimal ())
